version: 2
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/php:7.2.1-apache-node-browsers
      - image: circleci/mysql:5.7

jobs:
  aaa:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Echo
          command: echo hello, world.

workflows:
  version: 2
  build-test:
    jobs:
      - aaa
