version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/php:7.2.1-apache-node-browsers
      - image: circleci/mysql:5.7
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:HqZ6aVfJfMy/M68M/YcSEI7HIvHpnyTo8fV9TSKr+5I=
      - APP_URL: http://127.0.0.1:8000
      - DB_CONNECTION: mysql
      - DB_HOST: 127.0.0.1
      - DB_PORT: 3306
      - DB_DATABASE: circle_test
      - DB_USERNAME: root
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

commands:
  npm-install:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}

  composer-install:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: composer-{{ checksum "composer.lock" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Install dependencies
          command: composer install
      - save_cache:
          name: Cache composer dependencies
          key: composer-{{ checksum "composer.lock" }}-{{ .Environment.CACHE_VERSION_NPM }}
  test:
    steps:
      - composer_lint:
          name: composer lint
          command: composer lint
      - composer_phan:
          name: composer phan
          command: composer phan
jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - npm-install
      - composer-install
      - test

workflows:
  version: 2
  build:
    jobs:
      - build:
