version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/php:7.3.1-apache-node-browsers
      - image: circleci/mysql:5.7
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:HqZ6aVfJfMy/M68M/YcSEI7HIvHpnyTo8fV9TSKr+5I=
      - APP_URL: http://127.0.0.1:8000
      - DB_CONNECTION: mysql
      - DB_HOST: 127.0.0.1
      - DB_PORT: 3306
      - DB_DATABASE: circle_test
      - DB_USERNAME: root
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

commands:
  test-command:
    steps:
      - run:
          name: Echo
          command: echo hello, world.

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - test-command


workflows:
  version: 2
  build-test:
    jobs:
      - test
