version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/php:7.3.1-apache-node-browsers
      - image: circleci/mysql:5.7
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:HqZ6aVfJfMy/M68M/YcSEI7HIvHpnyTo8fV9TSKr+5I=
      - APP_URL: http://127.0.0.1:8000
      - DB_CONNECTION: mysql
      - DB_HOST: 127.0.0.1
      - DB_PORT: 3306
      - DB_DATABASE: circle_test
      - DB_USERNAME: root
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

commands:
  persist-to-workspace:
    - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  npm-install:
    steps:
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: install npm
          command: yarn
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
              - node_modules
  composer-install:
    steps:
      - restore_cache:
          key: composer-cache-{{ checksum "composer.json" }}
      - run:
          name: install composer
          command: composer install
      - save_cache:
          key: composer-cache-{{ checksum "composer.json" }}
          paths:
              - vendor
  lint:
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: phpcs
          command: composer lint
  phan:
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Install php-ast
          command: |
            cd ~
            git clone https://github.com/nikic/php-ast
            cd php-ast
            phpize
            ./configure
            make
            sudo make install
            echo -e "extension=ast.so" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run:
          name: phan
          command: composer phan

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - npm-install
      - composer-install
      - persist-to-workspace
  lint:
    executor:
      name: default
    steps:
      - lint
  phan:
    executor:
      name: default
    steps:
      - phan

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - phan:
          requires:
            - build
